### ISSUE TITLE
Unable to install Tags via Craft CMS Plugin store

### ISSUE THREAD

**Issue by afairhurst** [ethercreative/tags#1]
Updating Composer dependencies (this may take a minute)…

Status: HTTP/2.0 503

Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
<style>
body {margin: 20px; font-family: helvetica, sans-serif; max-width: 800px;}
.error {color: #e00;}
pre {font-size: 16px;}
h1 {font-size: 28px;}
</style>
</head><body>
<h1>Service Unavailable</h1>
<p>PHP did not respond properly to the request.
As a result, Apache considers the PHP-FPM service to be unavailable.</p>

<p class=error><b>Detailed information about this error is available in the app's Apache error log at:</b></p>
<pre class=error>/srv/users/SYSUSER/log/APPNAME/APPNAME_apache.error.log</pre>
<p><b>The root cause of this error is often slow PHP code.
You should disable any plugins the app is using and
check the app's PHP error log and PHP slow request log located at:</b></p>
<pre>/srv/users/SYSUSER/log/APPNAME/APPNAME_phpX.Y.error.log
/srv/users/SYSUSER/log/APPNAME/APPNAME_phpX.Y.slow.log</pre>
</body></html>

**Comment by afairhurst** [comment]
I've tried locally and on a staging site. Error is the same.

Really looking forward to trying this plugin; Thanks so much for developing it!

**Comment by proimage** [comment]
Installing directly via composer worked for me: `composer require ether/tags`

**Comment by Tam** [comment]
This seems like a Plugin store / Craft issue, possibly temporary. Have you been able to install it since?

**Comment by alexjcollins** [comment]
Hey @afairhurst did you manage to get the plugin installed in the end?
