### ISSUE TITLE
Error when trying to replace/merge tags

### ISSUE THREAD

**Issue by skoften** [ethercreative/tags#13]
When merging/replacing tags, you can't the save button due to an JS error;

![Screenshot 2020-02-18 at 15 07 57](https://user-images.githubusercontent.com/1286410/74743614-048ee380-5261-11ea-8b83-bb8d30b33a51.jpg)

Running Craft CMS 3.4.5, PHP 7.2

**Comment by rgbjay** [comment]
Also seeing this issue using Craft 3.4.5
