### ISSUE TITLE
Recent Craft update causes no tags to be listed at `/admin/tags`

### ISSUE THREAD

**Issue by meestaben** [ethercreative/tags#18]
Hi,

It appears that this recent Craft update has broken the list view:

https://github.com/craftcms/cms/commit/636f7783a953d589bd22feb3f75253eb66cd938a

When visiting `/admin/tags` no tags are listed (either when choosing 'All Tags' or when selecting a specific Tag Group)

Creating/editing tags works fine, it's just the list view which seems to be broken.

Craft version: 3.7.12
Plugin version: 1.0.7

**Comment by alexjcollins** [comment]
@meestaben Right you are!

@Tam Could you pick this one up for me? Cheers!

**Comment by Reddogdesigns** [comment]
I'm also having this issue. Is there a rough timeline on when this might be resolved?

Thanks

**Comment by joomkit** [comment]
Had a quick look at fixing but couldn't quite work out what was missing - i think its missing a line in the db specifying what element type the tag.plugin is. Anyway I need to work around this and commenting out line 1440 [here](https://github.com/craftcms/cms/commit/636f7783a953d589bd22feb3f75253eb66cd938a) seems to provide a temporary work around

**Comment by stevecomrie** [comment]
I've got a potential fix for this submitted as a pull request : https://github.com/ethercreative/tags/pull/19

**Comment by CreateSean** [comment]
Having same issue

**Comment by joomkit** [comment]
Quick solution is here: https://github.com/ethercreative/tags/pull/19#issuecomment-929341002

**Comment by membla** [comment]
> It appears that the Craft change that caused the breakage in the first place will be reversed in the next release:
> 
> [craftcms/cms@509962a](https://github.com/craftcms/cms/commit/509962a6656a19c309a251aa52f29802c542b5a7)

Thought this was the reason for #21 but downgrading to 1.0.7 did not solve for me. Would be awesome with a new fix for this.

**Comment by joomkit** [comment]
NB it seems ordering by title makes tags appear for me

**Comment by markus-antoni** [comment]
For me on 3.7.36 it still (or again) doesn't work to see new added tags in /admin/tags. The count of tags is correct, but to see new added tag, I need to reorder or clear cache.
